name: Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4', 'head']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run linter
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install yarn dep
      run: yarn install
    - name: Check prettier
      run: yarn prettier -c lib/**/*.rb spec/**/*.rb *.gemspec Gemfile
